- shell: apt-get update
- shell: apt-get -qq install -y
- shell: sudo libpq-dev postgresql postgresql-contrib -y -qq
- shell: sudo postgresql-client-common
- shell: dialog apt-utils
- shell: nodejs npm nodejs-legacy -y -qq
- shell: python-pip
- shell: python-dev
- shell: python-virtualenv
- shell: apache2
- shell: pip install --upgrade pip
- shell: mkdir /webapp && mkdir $WEBAPP_DIR
- name: Ensure  exists
  file:
    path: ''
    state: directory
- copy:
    src: basic-dep.sh
    dest: "{{ lookup('env', 'WEBAPP_DIR') }}"
- shell: cd $WEBAPP_DIR
  args:
    chdir: "{{ lookup('env', 'WEBAPP_DIR') }}"
- shell: chmod 700 basic-dep.sh
  args:
    chdir: "{{ lookup('env', 'WEBAPP_DIR') }}"
- shell: ./basic-dep.sh
  args:
    chdir: "{{ lookup('env', 'WEBAPP_DIR') }}"
- name: Ensure  exists
  file:
    path: ''
    state: directory
- copy:
    src: requirements.txt
    dest: "{{ lookup('env', 'WEBAPP_DIR') }}"
- shell: pip install -r requirements.txt
  args:
    chdir: "{{ lookup('env', 'WEBAPP_DIR') }}"
- name: Ensure  exists
  file:
    path: ''
    state: directory
- copy:
    src: manage.py
    dest: "{{ lookup('env', 'WEBAPP_DIR') }}"
- name: Ensure {{ lookup('env', 'WEBAPP_DIR') }} exists
  file:
    path: "{{ lookup('env', 'WEBAPP_DIR') }}"
    state: directory
- name: ADD ShowcaseServer $WEBAPP_DIR/ShowcaseServer (showcase_server)
  synchronize:
    src: showcase_server
    dest: "{{ lookup('env', 'WEBAPP_DIR') }}/showcase_server"
    recursive: yes
- name: Ensure {{ lookup('env', 'WEBAPP_DIR') }} exists
  file:
    path: "{{ lookup('env', 'WEBAPP_DIR') }}"
    state: directory
- synchronize:
    src: backend
    dest: "{{ lookup('env', 'WEBAPP_DIR') }}/backend"
    recursive: yes
- name: Ensure {{ lookup('env', 'WEBAPP_DIR') }} exists
  file:
    path: "{{ lookup('env', 'WEBAPP_DIR') }}"
    state: directory
- synchronize:
    src: dashboard
    dest: "{{ lookup('env', 'WEBAPP_DIR') }}/dashboard"
    recursive: yes
- name: Ensure  exists
  file:
    path: ''
    state: directory
- copy:
    src: dev-setup.sh
    dest: "{{ lookup('env', 'WEBAPP_DIR') }}"
- shell: cd $WEBAPP_DIR
  args:
    chdir: "{{ lookup('env', 'WEBAPP_DIR') }}"
- shell: chmod 700 dev-setup.sh
  args:
    chdir: "{{ lookup('env', 'WEBAPP_DIR') }}"
- shell: ./dev-setup.sh
  args:
    chdir: "{{ lookup('env', 'WEBAPP_DIR') }}"
