- name: Add the PostgreSQL PGP key to verify their Debian packages. It should be the
    same key as https://www.postgresql.org/media/keys/ACCC4CF8.asc
  shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys
    B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
- name: Add PostgreSQL's repository. It contains the most recent stable release of
    PostgreSQL, ``9.3``.
  shell: echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main" > /etc/apt/sources.list.d/pgdg.list
- name: Install ``python-software-properties``, ``software-properties-common`` and
    PostgreSQL 9.3 There are some warnings (in red) that show up during the build.
    You can hide them by prefixing each apt-get statement with DEBIAN_FRONTEND=noninteractive
  shell: apt-get update && apt-get install -y python-software-properties software-properties-common
    postgresql-9.3 postgresql-client-9.3 postgresql-contrib-9.3 gedit
- name: Adjust PostgreSQL configuration so that remote connections to the database
    are possible.
  shell: echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/9.3/main/pg_hba.conf
- name: And add ``listen_addresses`` to ``/etc/postgresql/9.3/main/postgresql.conf``
  shell: echo "listen_addresses='*'" >> /etc/postgresql/9.3/main/postgresql.conf
- shell: mkdir $DIR_DB
- name: Ensure  exists
  file:
    path: ''
    state: directory
  remote_user: postgres
- copy:
    src: init-db.sql
    dest: "{{ lookup('env', 'DIR_DB') }}"
  remote_user: postgres
- shell: service postgresql start
  remote_user: postgres
  args:
    chdir: "{{ lookup('env', 'DIR_DB') }}"
- shell: psql -a -f init-db.sql
  remote_user: postgres
  args:
    chdir: "{{ lookup('env', 'DIR_DB') }}"
- shell: service postgresql stop
  remote_user: postgres
  args:
    chdir: "{{ lookup('env', 'DIR_DB') }}"
- name: Ensure  exists
  file:
    path: ''
    state: directory
  remote_user: postgres
- copy:
    src: postgresql-template.conf
    dest: "{{ lookup('env', 'DIR_DB') }}"
  remote_user: postgres
- shell: cd /etc/postgresql/9.3/main
  remote_user: postgres
  args:
    chdir: "{{ lookup('env', 'DIR_DB') }}"
- shell: chmod 700 postgresql.conf
  remote_user: postgres
  args:
    chdir: "{{ lookup('env', 'DIR_DB') }}"
- shell: echo "envsubst < $DIR_DB/postgresql-template.conf > ./postgresql.conf"
  remote_user: postgres
  args:
    chdir: "{{ lookup('env', 'DIR_DB') }}"
